### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by anhtienng** [IHTSDO/snowstorm-lite#11]
Hi,

I just found a small typo in an example.
[`http://snomed.info/sct/900000000000207008\version\20240131`](https://github.com/IHTSDO/snowstorm-lite/blob/master/docs/snomed-edition-uri-examples.md#:~:text=http%3A//snomed.info/sct/900000000000207008%5Cversion%5C20240131)
Should be `http://snomed.info/sct/900000000000207008/version/20240131`

**Comment by kaicode** [comment]
Thank you @anhtienng, this is fixed now.
