### ISSUE TITLE
MLDS Syndication is temporarily not working

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/snowstorm-lite#12]
The MLDS Syndication download is currently having authentication issues which are being investigated.
This issue will be removed when they are fixed. I've put a note in the README about this too.

**Comment by pgwilliams** [comment]
Ref MLDS-1131

**Comment by kaicode** [comment]
This is now fixed using Snowstorm Lite version 2.0.0 and above. The MLDS service was also patched.
