### ISSUE TITLE
FHIR native / ICD-10 supported?

### ISSUE THREAD

**Issue by vadi2** [IHTSDO/snowstorm-lite#8]
Thanks for this nice tool!

Are FHIR-native codesystems supported? Similarly, is ICD-10 supported?

**Comment by kaicode** [comment]
Snowstorm Lite is intended to be a tiny SNOMED CT FHIR terminology server. It only supports SNOMED CT, no FHIR native or ICD-10 codesystems are supported. The full [Snowstorm product can do that](https://github.com/IHTSDO/snowstorm/blob/master/docs/using-the-fhir-api.md).

**Comment by vadi2** [comment]
Thanks!
